# Generated by Django 4.2.28 on 2026-02-13 09:36

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='postwalk',
            fields=[
                ('walk_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('difficulty', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('type', models.IntegerField(choices=[(0, 'Circular'), (1, 'Out and Back'), (2, 'One Way')])),
                ('distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time_hours', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('time_minutes', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)])),
                ('photo', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('location', models.CharField(max_length=200)),
                ('coordinates', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('authorised', models.BooleanField(default=False)),
                ('featured', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='walks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
