# Generated by Django 4.2.28 on 2026-02-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_walk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postwalk',
            name='difficulty',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Moderate'), (2, 'Hard'), (3, 'Expert')], default=0),
        ),
    ]
