# Generated by Django 4.2.28 on 2026-02-27 09:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post_walk', '0004_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postwalk',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourite_walks', to=settings.AUTH_USER_MODEL),
        ),
    ]
